### ISSUE TITLE
Transactional NTFS

### ISSUE THREAD

**Issue by kiquenet** [rsevil/Transactions#1]
This library is NOT a wrapper of Transactional NTFS

Newer versions of Windows have something called TxF (Transactional NTFS) you can use. 

http://bartdesmet.net/blogs/bart/archive/2006/11/19/Windows-Vista-_2D00_-Introducing-TxF-in-C_2300_-_2800_part-2_2900_-_2D00_-Using-System.Transactions-and-the-DTC.aspx

```
 // // Make it transacted. // 
 using (TransactionScope tx = new TransactionScope()) 
 { 
// // Delete the files (transacted). // 
 DeleteFile(file1);
DeleteFile(file2); 

// // Commit or rollback? //  char c; 
do { 

                    Console.WriteLine("{0} {1}.", file1, System.IO.File.Exists(file1) ? "still exists" : "has vanished"); 

                    Console.WriteLine("{0} {1}.", file2, System.IO.File.Exists(file2) ? "still exists" : "has vanished"); 

                    Console.Write("Commit transaction (Y/N)? "); 

                    c = (char)Console.Read(); 

} 

while (c != 'Y' && c != 'y' && c != 'N' && c != 'n'); 




if (c == 'Y' || c == 'y') tx.Complete(); 

} 
```

https://stackoverflow.com/questions/7939339/how-to-write-a-transaction-to-cover-moving-a-file-and-inserting-record-in-databa

**Comment by rsevil** [comment]
Hi @kiquenet,

Sorry for the late reply, I don't understand why did you create this as an issue since in Readme.md it is clearly stated that this library is not a wrapper of Transactional NTFS (TxF).

Can you clarify please?

**Comment by rsevil** [comment]
Closing due to no response in 2 months
