### ISSUE TITLE
.NET Transactional File Manager project migrated to GitHub

### ISSUE THREAD

**Issue by chinhdo** [rsevil/Transactions#3]
Hi, FYI I migrated the original project for .NET Transactional File Manager from CodePlex to GitHub [here](https://github.com/chinhdo/txFileManager). This is Chinh, author of the original project. Thanks

**Comment by rsevil** [comment]
Hi @chinhdo, great news!

I'll archive this repository and leave a message over the Readme for people to go to your repository.
